package com.qfk.match.api;
import com.qfk.match.entity.*;import com.qfk.match.repository.*;import com.qfk.match.service.RegistrationService;import com.qfk.member.repository.MemberRepository;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.math.BigDecimal;import java.time.Instant;import java.util.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.security.oauth2.jwt.Jwt;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/matches") public class MatchController {private final MatchRepository matches;private final RegistrationRepository registrations;private final MemberRepository members;private final RegistrationService service;public MatchController(MatchRepository m,RegistrationRepository r,MemberRepository members,RegistrationService s){matches=m;registrations=r;this.members=members;service=s;}
 @GetMapping public List<MatchView> list(){return matches.findAll().stream().sorted(Comparator.comparing(m->m.startsAt,Comparator.nullsLast(Comparator.naturalOrder()))).map(this::view).toList();}
 private void apply(FootballMatch m,CreateMatch r){if(m.status!=null&&Set.of(FootballMatch.MatchStatus.COMPLETED,FootballMatch.MatchStatus.CANCELLED).contains(m.status)&&m.status!=r.status())throw new IllegalStateException("Terminal match status cannot be changed");if(r.status()==FootballMatch.MatchStatus.COMPLETED&&m.status!=FootballMatch.MatchStatus.COMPLETED&&(m.status!=FootballMatch.MatchStatus.IN_PROGRESS||m.homeScore==null))throw new IllegalStateException("Start the match and save a result before completing it");if(!r.endsAt().isAfter(r.startsAt()))throw new IllegalArgumentException("End time must follow start time");m.matchNumber=r.matchNumber();m.title=r.title();m.type=r.type();m.status=r.status();m.startsAt=r.startsAt();m.endsAt=r.endsAt();m.venue=r.venue();m.maximumPlayers=r.maximumPlayers();m.registrationFee=r.registrationFee();}
 @PostMapping @PreAuthorize("hasAnyRole('ADMIN','SUPER_ADMIN','ORGANIZER')") public MatchView create(@Valid @RequestBody CreateMatch r){var m=new FootballMatch();apply(m,r);return view(matches.save(m));}
 @PutMapping("/{id}") @PreAuthorize("hasAnyRole('ADMIN','SUPER_ADMIN','ORGANIZER')") @org.springframework.transaction.annotation.Transactional public MatchView update(@PathVariable UUID id,@Valid @RequestBody CreateMatch r){var m=matches.findByIdForRegistration(id).orElseThrow(()->new IllegalArgumentException("Match not found"));if(r.maximumPlayers()<registrations.countByMatchIdAndStatus(id,MatchRegistration.Status.CONFIRMED))throw new IllegalArgumentException("Capacity cannot be below confirmed registrations");apply(m,r);return view(matches.save(m));}
 public record NamedPlayers(@NotNull @Size(min=1,max=100) List<@NotBlank @Size(max=160) String> names){}
 @PostMapping("/{id}/players") @PreAuthorize("hasAnyRole('ADMIN','SUPER_ADMIN')") public List<RegistrationView> addPlayers(@PathVariable UUID id,@Valid @RequestBody NamedPlayers r){return service.addNamedPlayers(id,r.names()).stream().map(x->view(x,true)).toList();}
 public record AddMember(@NotNull UUID memberId){}
 @PostMapping("/{id}/members") @PreAuthorize("hasAnyRole('ADMIN','SUPER_ADMIN','ORGANIZER')") public RegistrationView addMember(@PathVariable UUID id,@Valid @RequestBody AddMember r){return view(service.register(id,members.findById(r.memberId()).orElseThrow(()->new IllegalArgumentException("Member not found"))));}
 @PostMapping("/{id}/guests") @PreAuthorize("hasAnyRole('ADMIN','SUPER_ADMIN','ORGANIZER')") public RegistrationView addGuest(@PathVariable UUID id,@Valid @RequestBody GuestMatchController.GuestInput r){return view(service.registerGuest(id,r.fullName(),r.mobile()),true);}
 @GetMapping("/{id}/registrations") public List<RegistrationView> registrations(@PathVariable UUID id,@AuthenticationPrincipal Jwt jwt){boolean manage=Set.of("ADMIN","SUPER_ADMIN","ORGANIZER").contains(jwt.getClaimAsString("role"));return registrations.findByMatchIdOrderByRegisteredAtAsc(id).stream().map(r->view(r,manage)).toList();}
 @PostMapping("/{id}/registrations") public RegistrationView register(@PathVariable UUID id,@AuthenticationPrincipal Jwt jwt){UUID memberId=UUID.fromString(jwt.getClaimAsString("memberId"));return view(service.register(id,members.findById(memberId).orElseThrow(()->new IllegalArgumentException("Member not found"))));}
 @DeleteMapping("/registrations/{id}") public void cancel(@PathVariable UUID id,@AuthenticationPrincipal Jwt jwt){var registration=registrations.findById(id).orElseThrow(()->new IllegalArgumentException("Registration not found"));String role=jwt.getClaimAsString("role");UUID memberId=UUID.fromString(jwt.getClaimAsString("memberId"));if((registration.member==null||!registration.member.id.equals(memberId))&&!java.util.Set.of("ADMIN","SUPER_ADMIN","ORGANIZER").contains(role))throw new org.springframework.security.access.AccessDeniedException("You cannot cancel this registration");service.cancel(id);}
 @PatchMapping("/registrations/{id}/payment") @PreAuthorize("hasAnyRole('ADMIN','SUPER_ADMIN','ORGANIZER')") public RegistrationView payment(@PathVariable UUID id,@Valid @RequestBody PaymentUpdate r){var x=registrations.findById(id).orElseThrow(()->new IllegalArgumentException("Registration not found"));x.paymentStatus=r.status();return view(registrations.save(x));}
 @PatchMapping("/registrations/{id}/attendance") @PreAuthorize("hasAnyRole('ADMIN','SUPER_ADMIN','ORGANIZER')") public RegistrationView attendance(@PathVariable UUID id,@Valid @RequestBody AttendanceUpdate r){var x=registrations.findById(id).orElseThrow(()->new IllegalArgumentException("Registration not found"));x.attendanceStatus=r.status();return view(registrations.save(x));}
 private MatchView view(FootballMatch m){return new MatchView(m.id,m.matchNumber,m.title,m.type,m.status,m.startsAt,m.endsAt,m.venue,m.maximumPlayers,m.registrationFee,m.currency,registrations.countByMatchIdAndStatus(m.id,MatchRegistration.Status.CONFIRMED));}
 private RegistrationView view(MatchRegistration r){return view(r,false);} private RegistrationView view(MatchRegistration r,boolean manage){return new RegistrationView(r.id,r.member==null?null:r.member.id,r.member==null?r.guestName:r.member.fullName,r.status,r.waitlistPosition,r.paymentStatus,r.attendanceStatus,r.registeredAt,r.member==null,manage?r.guestMobile:null);}
 public record CreateMatch(@Positive long matchNumber,@NotBlank String title,@NotNull FootballMatch.MatchType type,@NotNull FootballMatch.MatchStatus status,@NotNull Instant startsAt,@NotNull Instant endsAt,@NotBlank String venue,@Min(2) int maximumPlayers,@PositiveOrZero BigDecimal registrationFee){} public record PaymentUpdate(@NotNull MatchRegistration.PaymentStatus status){} public record AttendanceUpdate(@NotNull MatchRegistration.AttendanceStatus status){} public record MatchView(UUID id,long matchNumber,String title,FootballMatch.MatchType type,FootballMatch.MatchStatus status,Instant startsAt,Instant endsAt,String venue,int maximumPlayers,BigDecimal registrationFee,String currency,long confirmedPlayers){} public record RegistrationView(UUID id,UUID memberId,String memberName,MatchRegistration.Status status,Integer waitlistPosition,MatchRegistration.PaymentStatus paymentStatus,MatchRegistration.AttendanceStatus attendanceStatus,Instant registeredAt,boolean guest,String guestMobile){}
}
