package com.qfk.operations;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/manage")
public class ManagementController {
 private static final String MANAGE="hasAnyRole('ADMIN','SUPER_ADMIN','ORGANIZER')", ADMIN="hasAnyRole('ADMIN','SUPER_ADMIN')";
 private final JdbcTemplate db;
 public ManagementController(JdbcTemplate db){this.db=db;}
 private UUID user(Jwt j){return UUID.fromString(j.getSubject());}
 private UUID member(Jwt j){return UUID.fromString(j.getClaimAsString("memberId"));}
 private List<Map<String,Object>> rows(String sql,Object...args){var result=db.queryForList(sql,args);for(var r:result)r.replaceAll((k,v)->v instanceof Timestamp t?t.toInstant().toString():v instanceof java.sql.Date d?d.toLocalDate().toString():v);return result;}
 private Map<String,Object> one(String sql,Object...args){var r=rows(sql,args);if(r.isEmpty())throw new IllegalArgumentException("Record not found");return r.getFirst();}
 private void choice(String v,String...allowed){if(!Arrays.asList(allowed).contains(v))throw new IllegalArgumentException("Invalid choice");}
 private Map<String,Object> lock(UUID id){return one("SELECT * FROM matches WHERE id=? FOR UPDATE",id);}
 private void editable(Map<String,Object> m){if(Set.of("COMPLETED","CANCELLED").contains(m.get("status")))throw new IllegalStateException("Completed or cancelled matches cannot be changed");}
 @GetMapping("/matches/{id}") @PreAuthorize(MANAGE)
 public Map<String,Object> match(@PathVariable UUID id){return Map.of("match",one("SELECT m.*,h.name AS home_name,a.name AS away_name FROM matches m LEFT JOIN teams h ON h.id=m.home_team_id LEFT JOIN teams a ON a.id=m.away_team_id WHERE m.id=?",id),"roster",rows("SELECT r.*,coalesce(m.full_name,r.guest_name) AS player_name,m.email AS member_email,l.side,l.position,l.starter,l.pitch_x,l.pitch_y,l.shirt_number,coalesce(s.goals,g.goals,0) AS goals,coalesce(s.assists,g.assists,0) AS assists FROM match_registrations r LEFT JOIN members m ON m.id=r.member_id LEFT JOIN match_lineups l ON l.registration_id=r.id LEFT JOIN player_match_statistics s ON s.match_id=r.match_id AND s.member_id=r.member_id LEFT JOIN guest_match_statistics g ON g.registration_id=r.id WHERE r.match_id=? ORDER BY r.registered_at",id));}
 public record StatusInput(@NotBlank String status){}
 @PutMapping("/matches/{id}/status") @PreAuthorize(MANAGE) @Transactional
 public void status(@PathVariable UUID id,@Valid @RequestBody StatusInput r){choice(r.status(),"REGISTRATION_OPEN","REGISTRATION_CLOSED","TEAM_SELECTION","CONFIRMED","IN_PROGRESS","COMPLETED","CANCELLED");var m=lock(id);editable(m);if(r.status().equals("REGISTRATION_OPEN")){if(!Instant.parse(m.get("starts_at").toString()).isAfter(Instant.now()))throw new IllegalStateException("A started match cannot reopen registration");long n=db.queryForObject("SELECT count(*) FROM match_registrations WHERE match_id=? AND status='CONFIRMED'",Long.class,id);db.update("UPDATE matches SET status=?,version=version+1 WHERE id=?",n>=((Number)m.get("maximum_players")).intValue()?"FULL":r.status(),id);}else{if(r.status().equals("IN_PROGRESS")&&!Set.of("CONFIRMED","REGISTRATION_CLOSED","TEAM_SELECTION").contains(m.get("status")))throw new IllegalStateException("Close registration before starting the match");if(r.status().equals("COMPLETED")&&(m.get("home_score")==null||!m.get("status").equals("IN_PROGRESS")))throw new IllegalStateException("Start the match and save its result before completing it");db.update("UPDATE matches SET status=?,version=version+1 WHERE id=?",r.status(),id);}}
 public record TeamsInput(UUID homeTeamId,UUID awayTeamId){}
 @PutMapping("/matches/{id}/teams") @PreAuthorize(MANAGE) @Transactional
 public void teams(@PathVariable UUID id,@RequestBody TeamsInput r){editable(lock(id));if(r.homeTeamId()!=null&&r.homeTeamId().equals(r.awayTeamId()))throw new IllegalArgumentException("Choose different teams");for(UUID t:new UUID[]{r.homeTeamId(),r.awayTeamId()})if(t!=null)one("SELECT id FROM teams WHERE id=? AND active=true",t);db.update("UPDATE matches SET home_team_id=?,away_team_id=?,version=version+1 WHERE id=?",r.homeTeamId(),r.awayTeamId(),id);}
 public record LineupInput(@NotBlank String side,@NotBlank @Size(max=40) String position,boolean starter){}
 @PutMapping("/matches/{id}/lineup/{registrationId}") @PreAuthorize(MANAGE) @Transactional
 public void lineup(@PathVariable UUID id,@PathVariable UUID registrationId,@Valid @RequestBody LineupInput r){editable(lock(id));choice(r.side(),"HOME","AWAY","UNASSIGNED");choice(r.position(),"GOALKEEPER","DEFENDER","MIDFIELDER","FORWARD","UTILITY");one("SELECT id FROM match_registrations WHERE id=? AND match_id=? AND status='CONFIRMED'",registrationId,id);if(r.side().equals("UNASSIGNED"))db.update("DELETE FROM match_lineups WHERE registration_id=?",registrationId);else db.update("INSERT INTO match_lineups(registration_id,side,position,starter) VALUES(?,?,?,?) ON CONFLICT(registration_id) DO UPDATE SET side=excluded.side,position=excluded.position,starter=excluded.starter",registrationId,r.side(),r.position(),r.starter());}
 @PostMapping("/matches/{id}/balance") @PreAuthorize(MANAGE) @Transactional
 public void balance(@PathVariable UUID id){editable(lock(id));var players=rows("SELECT r.id,coalesce(s.goals,0)+coalesce(g.goals,0) AS rating FROM match_registrations r LEFT JOIN player_match_statistics s ON s.match_id=r.match_id AND s.member_id=r.member_id LEFT JOIN guest_match_statistics g ON g.registration_id=r.id WHERE r.match_id=? AND r.status='CONFIRMED' ORDER BY rating DESC,r.registered_at",id);int i=0;for(var p:players){String side=((i++/2)%2==0?(i%2==1?"HOME":"AWAY"):(i%2==1?"AWAY":"HOME"));db.update("INSERT INTO match_lineups(registration_id,side) VALUES(?,?) ON CONFLICT(registration_id) DO UPDATE SET side=excluded.side",p.get("id"),side);}}
 public record ResultInput(@Min(0) int homeScore,@Min(0) int awayScore){}
 @PutMapping("/matches/{id}/result") @PreAuthorize(MANAGE) @Transactional
 public void result(@PathVariable UUID id,@Valid @RequestBody ResultInput r){var m=lock(id);editable(m);if(!m.get("status").equals("IN_PROGRESS"))throw new IllegalStateException("Start the match before saving its result");db.update("UPDATE matches SET home_score=?,away_score=?,version=version+1 WHERE id=?",r.homeScore(),r.awayScore(),id);}
 public record PlayerStats(@Min(0) int goals,@Min(0) int assists){}
 @PutMapping("/matches/{id}/statistics/{registrationId}") @PreAuthorize(MANAGE) @Transactional
 public void statistics(@PathVariable UUID id,@PathVariable UUID registrationId,@Valid @RequestBody PlayerStats s,@AuthenticationPrincipal Jwt jwt){lock(id);var r=one("SELECT member_id FROM match_registrations WHERE id=? AND match_id=? AND status='CONFIRMED'",registrationId,id);if(r.get("member_id")==null)db.update("INSERT INTO guest_match_statistics(registration_id,goals,assists) VALUES(?,?,?) ON CONFLICT(registration_id) DO UPDATE SET goals=excluded.goals,assists=excluded.assists",registrationId,s.goals(),s.assists());else db.update("INSERT INTO player_match_statistics(match_id,member_id,goals,assists,updated_by) VALUES(?,?,?,?,?) ON CONFLICT(match_id,member_id) DO UPDATE SET goals=excluded.goals,assists=excluded.assists,updated_by=excluded.updated_by,updated_at=now()",id,r.get("member_id"),s.goals(),s.assists(),user(jwt));}
 public record BuilderPlayer(@NotNull UUID registrationId,@NotBlank String side,@NotBlank String position,boolean starter,@NotNull @DecimalMin("0") @DecimalMax("100") Double x,@NotNull @DecimalMin("0") @DecimalMax("100") Double y,@Min(1) @Max(99) Integer shirtNumber){}
 public record BuilderInput(@Min(5) @Max(11) int starterLimit,@NotBlank @Size(max=80) String homeName,@NotBlank @Size(max=80) String awayName,@Pattern(regexp="#([A-Fa-f0-9]{6})") @NotNull String homeColor,@Pattern(regexp="#([A-Fa-f0-9]{6})") @NotNull String awayColor,@NotNull @Size(max=200) List<@Valid BuilderPlayer> players){}
 @GetMapping("/matches/{id}/builder") @PreAuthorize(MANAGE) public Map<String,Object> builder(@PathVariable UUID id){one("SELECT id FROM matches WHERE id=?",id);var settings=rows("SELECT * FROM match_lineup_settings WHERE match_id=?",id);return settings.isEmpty()?Map.of("starter_limit",7,"home_name","Home squad","away_name","Away squad","home_color","#801735","away_color","#475463"):settings.getFirst();}
 @PutMapping("/matches/{id}/builder") @PreAuthorize(MANAGE) @Transactional public void saveBuilder(@PathVariable UUID id,@Valid @RequestBody BuilderInput r){editable(lock(id));if(!Set.of(5,7,9,11).contains(r.starterLimit()))throw new IllegalArgumentException("Choose 5, 7, 9 or 11 starters");Set<UUID> seen=new HashSet<>();Map<String,Integer> counts=new HashMap<>();for(var p:r.players()){if(!seen.add(p.registrationId()))throw new IllegalArgumentException("A player cannot appear twice");choice(p.side(),"HOME","AWAY","UNASSIGNED");choice(p.position(),"GOALKEEPER","DEFENDER","MIDFIELDER","FORWARD","UTILITY");one("SELECT id FROM match_registrations WHERE id=? AND match_id=? AND status='CONFIRMED'",p.registrationId(),id);if(!p.side().equals("UNASSIGNED")&&p.starter()&&counts.merge(p.side(),1,Integer::sum)>r.starterLimit())throw new IllegalArgumentException("Starter limit exceeded");}
 var existing=rows("SELECT l.registration_id,l.side,l.starter FROM match_lineups l JOIN match_registrations r ON r.id=l.registration_id WHERE r.match_id=? AND r.status='CONFIRMED'",id);for(var p:existing)if(!seen.contains(p.get("registration_id"))&&Boolean.TRUE.equals(p.get("starter"))&&counts.merge(p.get("side").toString(),1,Integer::sum)>r.starterLimit())throw new IllegalArgumentException("Starter limit exceeded");
 for(var p:r.players()){if(p.side().equals("UNASSIGNED"))db.update("DELETE FROM match_lineups WHERE registration_id=?",p.registrationId());else db.update("INSERT INTO match_lineups(registration_id,side,position,starter,pitch_x,pitch_y,shirt_number) VALUES(?,?,?,?,?,?,?) ON CONFLICT(registration_id) DO UPDATE SET side=excluded.side,position=excluded.position,starter=excluded.starter,pitch_x=excluded.pitch_x,pitch_y=excluded.pitch_y,shirt_number=excluded.shirt_number",p.registrationId(),p.side(),p.position(),p.starter(),p.x(),p.y(),p.shirtNumber());}
 db.update("INSERT INTO match_lineup_settings(match_id,starter_limit,home_name,away_name,home_color,away_color) VALUES(?,?,?,?,?,?) ON CONFLICT(match_id) DO UPDATE SET starter_limit=excluded.starter_limit,home_name=excluded.home_name,away_name=excluded.away_name,home_color=excluded.home_color,away_color=excluded.away_color",id,r.starterLimit(),r.homeName(),r.awayName(),r.homeColor(),r.awayColor());}
 @GetMapping("/members/{id}/history") @PreAuthorize(MANAGE)
 public Map<String,Object> history(@PathVariable UUID id){return Map.of("matches",rows("SELECT m.title,m.starts_at,r.status,r.payment_status,r.attendance_status,coalesce(s.goals,0) AS goals,coalesce(s.assists,0) AS assists FROM match_registrations r JOIN matches m ON m.id=r.match_id LEFT JOIN player_match_statistics s ON s.match_id=m.id AND s.member_id=r.member_id WHERE r.member_id=? ORDER BY m.starts_at DESC",id),"roles",rows("SELECT h.previous_role,h.new_role,h.changed_at FROM account_role_history h JOIN user_accounts u ON u.id=h.account_id WHERE u.member_id=? ORDER BY changed_at DESC",id));}
 public record RoleInput(@NotBlank String role){}
 @PutMapping("/members/{id}/role") @PreAuthorize(ADMIN) @Transactional
 public void role(@PathVariable UUID id,@Valid @RequestBody RoleInput r,@AuthenticationPrincipal Jwt jwt){choice(r.role(),"MEMBER","ORGANIZER","ADMIN");var u=one("SELECT * FROM user_accounts WHERE member_id=? FOR UPDATE",id);if(u.get("id").equals(user(jwt)))throw new IllegalStateException("Ask another admin to change your own role");if(u.get("role").equals("SUPER_ADMIN"))throw new IllegalStateException("Super admin roles cannot be changed here");db.update("INSERT INTO account_role_history(account_id,previous_role,new_role,changed_by) VALUES(?,?,?,?)",u.get("id"),u.get("role"),r.role(),user(jwt));db.update("UPDATE user_accounts SET role=?,updated_at=now() WHERE id=?",r.role(),u.get("id"));}
 @GetMapping("/teams/{id}/history") public Map<String,Object> teamHistory(@PathVariable UUID id){return Map.of("matches",rows("SELECT id,title,starts_at,status,home_score,away_score,CASE WHEN home_team_id=? THEN 'HOME' ELSE 'AWAY' END AS side FROM matches WHERE home_team_id=? OR away_team_id=? ORDER BY starts_at DESC",id,id,id),"fixtures",rows("SELECT f.*,h.name AS home_name,a.name AS away_name FROM tournament_fixtures f JOIN teams h ON h.id=f.home_team_id JOIN teams a ON a.id=f.away_team_id WHERE home_team_id=? OR away_team_id=? ORDER BY starts_at DESC",id,id),"lineups",rows("SELECT x.title,coalesce(m.full_name,r.guest_name) AS player,l.side,l.position,l.starter FROM match_lineups l JOIN match_registrations r ON r.id=l.registration_id LEFT JOIN members m ON m.id=r.member_id JOIN matches x ON x.id=r.match_id WHERE (l.side='HOME' AND x.home_team_id=?) OR(l.side='AWAY' AND x.away_team_id=?) ORDER BY x.starts_at DESC,player",id,id));}
 @GetMapping("/finance/fees") @PreAuthorize(ADMIN)
 public List<Map<String,Object>> fees(){return rows("SELECT r.id,coalesce(m.full_name,r.guest_name) AS player,r.member_id,x.id AS match_id,x.title,x.starts_at,x.registration_fee,x.currency,r.payment_status,CASE WHEN r.payment_status='PENDING' THEN x.registration_fee ELSE 0 END AS outstanding FROM match_registrations r JOIN matches x ON x.id=r.match_id LEFT JOIN members m ON m.id=r.member_id WHERE r.status='CONFIRMED' ORDER BY x.starts_at DESC,player");}
 @GetMapping("/finance/members/{id}") @PreAuthorize(ADMIN) public List<Map<String,Object>> payments(@PathVariable UUID id){return rows("SELECT f.id,f.kind,f.amount,f.category,f.description,f.occurred_on,f.voided_at,x.title FROM finance_entries f LEFT JOIN matches x ON x.id=f.match_id WHERE f.member_id=? ORDER BY occurred_on DESC",id);}
 @GetMapping("/finance/{id}/receipt") @PreAuthorize(ADMIN) public Map<String,Object> receipt(@PathVariable UUID id){return one("SELECT f.id,f.kind,f.amount,f.currency,f.category,f.description,f.occurred_on,f.created_at,f.voided_at,f.void_reason,m.full_name AS member_name,x.title AS match_title FROM finance_entries f LEFT JOIN members m ON m.id=f.member_id LEFT JOIN matches x ON x.id=f.match_id WHERE f.id=?",id);}
 @GetMapping("/statistics") public Map<String,Object> allStatistics(){return Map.of("guests",rows("SELECT r.guest_name AS player,count(*) FILTER(WHERE r.attendance_status='PRESENT') AS appearances,coalesce(sum(g.goals),0) AS goals,coalesce(sum(g.assists),0) AS assists FROM match_registrations r LEFT JOIN guest_match_statistics g ON g.registration_id=r.id WHERE r.member_id IS NULL GROUP BY r.guest_mobile,r.guest_name ORDER BY goals DESC,player"),"trends",rows("SELECT to_char(m.starts_at AT TIME ZONE 'Asia/Qatar','YYYY-MM') AS month,count(DISTINCT m.id) AS matches,count(r.id) FILTER(WHERE r.attendance_status='PRESENT') AS attendance,coalesce(sum(s.goals),0)+coalesce(sum(g.goals),0) AS goals,coalesce(sum(s.assists),0)+coalesce(sum(g.assists),0) AS assists FROM matches m LEFT JOIN match_registrations r ON r.match_id=m.id LEFT JOIN player_match_statistics s ON s.match_id=m.id AND s.member_id=r.member_id LEFT JOIN guest_match_statistics g ON g.registration_id=r.id WHERE m.status<>'CANCELLED' GROUP BY month ORDER BY month"),"teams",rows("WITH games AS(SELECT home_team_id AS id,home_score AS gf,away_score AS ga FROM matches WHERE status='COMPLETED' UNION ALL SELECT away_team_id,away_score,home_score FROM matches WHERE status='COMPLETED' UNION ALL SELECT home_team_id,home_score,away_score FROM tournament_fixtures WHERE home_score IS NOT NULL UNION ALL SELECT away_team_id,away_score,home_score FROM tournament_fixtures WHERE home_score IS NOT NULL) SELECT t.id,t.name,count(g.id) AS played,count(*) FILTER(WHERE gf>ga) AS wins,count(*) FILTER(WHERE gf=ga) AS draws,count(*) FILTER(WHERE gf<ga) AS losses,coalesce(sum(gf),0) AS goals_for,coalesce(sum(ga),0) AS goals_against FROM teams t LEFT JOIN games g ON g.id=t.id GROUP BY t.id,t.name ORDER BY wins DESC,t.name"));}
 @GetMapping("/notifications") public List<Map<String,Object>> notifications(@AuthenticationPrincipal Jwt jwt){return rows("SELECT a.id,a.title,a.body,a.priority,coalesce(a.publish_at,a.created_at) AS published_at,r.read_at FROM announcements a LEFT JOIN announcement_reads r ON r.announcement_id=a.id AND r.member_id=? WHERE a.status='PUBLISHED' AND(a.publish_at IS NULL OR a.publish_at<=now()) AND(a.audience_team_id IS NULL OR EXISTS(SELECT 1 FROM team_members t WHERE t.team_id=a.audience_team_id AND t.member_id=? AND t.left_at IS NULL)) ORDER BY published_at DESC",member(jwt),member(jwt));}
 @PostMapping("/notifications/{id}/read") public void read(@PathVariable UUID id,@AuthenticationPrincipal Jwt jwt){one("SELECT id FROM announcements a WHERE id=? AND status='PUBLISHED' AND(publish_at IS NULL OR publish_at<=now()) AND(audience_team_id IS NULL OR EXISTS(SELECT 1 FROM team_members t WHERE t.team_id=a.audience_team_id AND t.member_id=? AND t.left_at IS NULL))",id,member(jwt));db.update("INSERT INTO announcement_reads(announcement_id,member_id) VALUES(?,?) ON CONFLICT DO NOTHING",id,member(jwt));}
}
