package com.qfk.operations;
import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.time.*;import java.sql.Timestamp;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/manage/tournaments") @PreAuthorize("hasAnyRole('ADMIN','SUPER_ADMIN','ORGANIZER')")
public class TournamentPlanner{
 private final JdbcTemplate db;public TournamentPlanner(JdbcTemplate d){db=d;}
 private Map<String,Object> lock(UUID id){var t=db.queryForList("SELECT * FROM tournaments WHERE id=? AND status IN('DRAFT','OPEN','IN_PROGRESS') FOR UPDATE",id);if(t.isEmpty())throw new IllegalStateException("Tournament is not editable");return t.getFirst();}
 public record GroupInput(@NotNull UUID teamId,@NotBlank @Pattern(regexp="[A-Z0-9]{1,10}") String groupName){}
 @PutMapping("/{id}/groups") @Transactional public void group(@PathVariable UUID id,@Valid @RequestBody GroupInput r){lock(id);if(db.queryForObject("SELECT count(*) FROM tournament_fixtures WHERE tournament_id=?",Integer.class,id)>0)throw new IllegalStateException("Assign groups before generating fixtures");if(db.update("UPDATE tournament_teams SET group_name=? WHERE tournament_id=? AND team_id=?",r.groupName(),id,r.teamId())!=1)throw new IllegalArgumentException("Enroll the team first");}
 public record GenerateInput(@NotBlank String format,@NotNull Instant startsAt,@Min(5) @Max(1440) int intervalMinutes){}
 private void insert(UUID id,UUID home,UUID away,Instant at,String stage,int round,String group){db.update("INSERT INTO tournament_fixtures(tournament_id,home_team_id,away_team_id,starts_at,stage,round_number,group_name) VALUES(?,?,?,?,?,?,?)",id,home,away,Timestamp.from(at),stage,round,group);}
 private void date(Map<String,Object> t,Instant at){var day=at.atZone(ZoneId.of("Asia/Qatar")).toLocalDate();if(day.isBefore(((java.sql.Date)t.get("starts_on")).toLocalDate())||day.isAfter(((java.sql.Date)t.get("ends_on")).toLocalDate()))throw new IllegalArgumentException("The generated schedule exceeds tournament dates");}
 @PostMapping("/{id}/generate") @Transactional public void generate(@PathVariable UUID id,@Valid @RequestBody GenerateInput r){var t=lock(id);if(!Set.of("LEAGUE","GROUP","KNOCKOUT").contains(r.format()))throw new IllegalArgumentException("Choose league, groups, or knockout");if(db.queryForObject("SELECT count(*) FROM tournament_fixtures WHERE tournament_id=?",Integer.class,id)>0)throw new IllegalStateException("Fixtures already exist; generation cannot replace them");var teams=db.queryForList("SELECT team_id,group_name FROM tournament_teams WHERE tournament_id=? ORDER BY group_name,team_id",id);if(teams.size()<2||teams.size()>32)throw new IllegalArgumentException("Enroll between 2 and 32 teams");if(r.format().equals("GROUP")){Map<String,Integer> groups=new HashMap<>();for(var team:teams)groups.merge(team.get("group_name").toString(),1,Integer::sum);if(groups.values().stream().anyMatch(n->n<2))throw new IllegalArgumentException("Each group needs at least two teams");}Instant at=r.startsAt();if(r.format().equals("KNOCKOUT")){if(Integer.bitCount(teams.size())!=1)throw new IllegalArgumentException("Knockout requires 2, 4, 8, 16, or 32 teams");for(int i=0;i<teams.size();i+=2){date(t,at);insert(id,(UUID)teams.get(i).get("team_id"),(UUID)teams.get(i+1).get("team_id"),at,"KNOCKOUT",1,null);at=at.plusSeconds(60L*r.intervalMinutes());}}else{for(int i=0;i<teams.size();i++)for(int j=i+1;j<teams.size();j++){var a=teams.get(i);var b=teams.get(j);if(r.format().equals("GROUP")&&!a.get("group_name").equals(b.get("group_name")))continue;date(t,at);insert(id,(UUID)a.get("team_id"),(UUID)b.get("team_id"),at,r.format(),1,r.format().equals("GROUP")?a.get("group_name").toString():null);at=at.plusSeconds(60L*r.intervalMinutes());}if(db.queryForObject("SELECT count(*) FROM tournament_fixtures WHERE tournament_id=?",Integer.class,id)==0)throw new IllegalArgumentException("Each group needs at least two teams");}}
 public record WinnerInput(@NotNull UUID winnerTeamId){}
 @PutMapping("/fixtures/{id}/winner") @Transactional public void winner(@PathVariable UUID id,@Valid @RequestBody WinnerInput r){var list=db.queryForList("SELECT * FROM tournament_fixtures WHERE id=?",id);if(list.isEmpty())throw new IllegalArgumentException("Fixture not found");var f=list.getFirst();lock((UUID)f.get("tournament_id"));if(f.get("home_score")==null)throw new IllegalStateException("Save a score first");if(!r.winnerTeamId().equals(f.get("home_team_id"))&&!r.winnerTeamId().equals(f.get("away_team_id")))throw new IllegalArgumentException("Winner must be a fixture team");int h=((Number)f.get("home_score")).intValue(),a=((Number)f.get("away_score")).intValue();if(h!=a&&!r.winnerTeamId().equals(h>a?f.get("home_team_id"):f.get("away_team_id")))throw new IllegalArgumentException("Winner must match the score");if(db.queryForObject("SELECT count(*) FROM tournament_fixtures WHERE tournament_id=? AND stage='KNOCKOUT' AND round_number>?",Integer.class,f.get("tournament_id"),f.get("round_number"))>0)throw new IllegalStateException("The next round already exists");db.update("UPDATE tournament_fixtures SET winner_team_id=? WHERE id=?",r.winnerTeamId(),id);}
 public record AdvanceInput(@NotNull Instant startsAt,@Min(5) @Max(1440) int intervalMinutes,@Min(1) @Max(4) int qualifiersPerGroup){}
 @PostMapping("/{id}/advance") @Transactional public void advance(@PathVariable UUID id,@Valid @RequestBody AdvanceInput r){var t=lock(id);Integer round=db.queryForObject("SELECT coalesce(max(round_number),0) FROM tournament_fixtures WHERE tournament_id=? AND stage='KNOCKOUT'",Integer.class,id);List<UUID> qualifiers=new ArrayList<>();if(round>0){var fs=db.queryForList("SELECT * FROM tournament_fixtures WHERE tournament_id=? AND stage='KNOCKOUT' AND round_number=? ORDER BY starts_at,id",id,round);for(var f:fs){if(f.get("home_score")==null)throw new IllegalStateException("Finish every fixture before advancing");int h=((Number)f.get("home_score")).intValue(),a=((Number)f.get("away_score")).intValue();UUID winner=(UUID)(h==a?f.get("winner_team_id"):h>a?f.get("home_team_id"):f.get("away_team_id"));if(winner==null)throw new IllegalStateException("Choose a penalty winner for drawn knockout fixtures");qualifiers.add(winner);}}else{if(db.queryForObject("SELECT count(*) FROM tournament_fixtures WHERE tournament_id=? AND stage='GROUP'",Integer.class,id)==0)throw new IllegalStateException("Generate group or knockout fixtures first");if(db.queryForObject("SELECT count(*) FROM tournament_fixtures WHERE tournament_id=? AND home_score IS NULL",Integer.class,id)>0)throw new IllegalStateException("Finish the group stage first");var ranked=db.queryForList("WITH results AS(SELECT home_team_id AS team_id,home_score AS gf,away_score AS ga FROM tournament_fixtures WHERE tournament_id=? AND stage='GROUP' UNION ALL SELECT away_team_id,away_score,home_score FROM tournament_fixtures WHERE tournament_id=? AND stage='GROUP') SELECT tt.team_id,tt.group_name,coalesce(sum(CASE WHEN gf>ga THEN 3 WHEN gf=ga THEN 1 ELSE 0 END),0) AS points,coalesce(sum(gf-ga),0) AS gd,coalesce(sum(gf),0) AS gf FROM tournament_teams tt LEFT JOIN results r ON r.team_id=tt.team_id WHERE tt.tournament_id=? GROUP BY tt.team_id,tt.group_name ORDER BY group_name,points DESC,gd DESC,gf DESC,tt.team_id",id,id,id);Map<String,Integer> counts=new HashMap<>();for(var q:ranked){String g=q.get("group_name").toString();int n=counts.merge(g,1,Integer::sum);if(n<=r.qualifiersPerGroup())qualifiers.add((UUID)q.get("team_id"));}round=0;}
 if(qualifiers.size()==1)throw new IllegalStateException("The tournament already has a champion");if(qualifiers.size()<2||Integer.bitCount(qualifiers.size())!=1)throw new IllegalArgumentException("The qualifier count must be 2, 4, 8, 16, or 32");Instant at=r.startsAt();for(int i=0;i<qualifiers.size()/2;i++){date(t,at);insert(id,qualifiers.get(i),qualifiers.get(qualifiers.size()-1-i),at,"KNOCKOUT",round+1,null);at=at.plusSeconds(60L*r.intervalMinutes());}}
}
