package com.qfk.auth.api;
import com.qfk.auth.entity.UserAccount;import com.qfk.auth.repository.UserAccountRepository;import com.qfk.auth.service.PasswordResetService;import com.qfk.auth.service.TokenService;import com.qfk.member.entity.Member;import com.qfk.member.repository.MemberRepository;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.http.ResponseEntity;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/auth") public class AuthController {private final UserAccountRepository users;private final MemberRepository members;private final PasswordEncoder passwords;private final TokenService tokens;private final PasswordResetService passwordResets;public AuthController(UserAccountRepository u,MemberRepository m,PasswordEncoder p,TokenService t,PasswordResetService pr){users=u;members=m;passwords=p;tokens=t;passwordResets=pr;}
 @PostMapping("/register") @Transactional public TokenService.Tokens register(@Valid @RequestBody RegisterRequest r){String email=r.email().trim().toLowerCase();if(users.existsByEmailIgnoreCase(email))throw new IllegalStateException("Email is already registered");var member=new Member();member.fullName=r.fullName().trim();member.email=email;member.joinedOn=java.time.LocalDate.now();members.save(member);var user=new UserAccount();user.member=member;user.email=email;user.passwordHash=passwords.encode(r.password());users.save(user);return tokens.issue(user);}
 @PostMapping("/login") public TokenService.Tokens login(@Valid @RequestBody LoginRequest r){var user=users.findByEmailIgnoreCase(r.email().trim()).filter(u->u.enabled).orElseThrow(()->new IllegalArgumentException("Invalid credentials"));if(!passwords.matches(r.password(),user.passwordHash))throw new IllegalArgumentException("Invalid credentials");return tokens.issue(user);}
 @PostMapping("/refresh") public TokenService.Tokens refresh(@Valid @RequestBody RefreshRequest r){return tokens.rotate(r.refreshToken());}
 @PostMapping("/forgot-password") public ResponseEntity<Void> forgotPassword(@Valid @RequestBody ForgotPasswordRequest r){passwordResets.request(r.email());return ResponseEntity.accepted().build();}
 @PostMapping("/reset-password") public ResponseEntity<Void> resetPassword(@Valid @RequestBody ResetPasswordRequest r){passwordResets.reset(r.token(),r.password());return ResponseEntity.noContent().build();}
 public record RegisterRequest(@NotBlank @Size(max=160) String fullName,@Email @NotBlank String email,@Size(min=10,max=100) String password){} public record LoginRequest(@Email @NotBlank String email,@NotBlank String password){} public record RefreshRequest(@NotBlank String refreshToken){} public record ForgotPasswordRequest(@Email @NotBlank String email){} public record ResetPasswordRequest(@NotBlank String token,@Size(min=10,max=100) String password){}
}
