import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,useNavigate} from 'react-router-dom';
import {CalendarDays,MapPin,Users,Trophy,Wallet,ChevronRight,Bell,LayoutDashboard,Shield,Menu,X,Clock,CheckCircle2,UserRound,ArrowUpRight,Activity,Goal,LogOut,Search,MoreHorizontal} from 'lucide-react';
import './global-styles.css';
import {AlternateHome} from './alternate-home';
import './alternate-home.css';
import {api,type Match,type Session} from './api-client';
import {CommandCenter,canManageMatches} from './command-center';

type View='public'|'matches'|'login'|'member'|'admin'|'command';
const games=[{day:'FRI',date:'11 SEP',title:'Friday Community Match #128',meta:'8:00 PM · Al Sadd Sports Club',slots:'14 / 16',tone:'open'},{day:'FRI',date:'18 SEP',title:'QFK Friday Night Football',meta:'8:30 PM · Doha Sports Park',slots:'Registration soon',tone:'soon'}];

function Brand({onHome}:{onHome?:()=>void}){return <button className="brand" onClick={onHome??(()=>location.hash='')}><img className="brand-crest" src={`${import.meta.env.BASE_URL}qfk-crest.png`} alt="QFK eagle crest"/><span><b>QFK</b><small>QATAR FOOTBALL KOOTTAM</small></span></button>}
function App(){const resetToken=new URLSearchParams(location.search).get('resetToken')??'';const [view,setView]=useState<View>(location.pathname==='/alternate'?'alternate' as View:resetToken?'login':'public'); const [menu,setMenu]=useState(false); const [session,setSession]=useState<Session|null>(api.getSession());
 useEffect(()=>{const sync=()=>setSession(api.getSession());window.addEventListener('qfk-session-changed',sync);return ()=>window.removeEventListener('qfk-session-changed',sync)},[]);
 if((view as string)==='alternate') return <AlternateHome onEnter={()=>setView('member')} onOriginal={()=>{history.pushState({},'', '/');setView('public')}}/>;
 if(view==='public') return <Public session={session} onMatches={()=>setView('matches')} onLogin={()=>setView(session?'matches':'login')}/>;
 if(view==='login') return <AuthScreen resetToken={resetToken} onBack={()=>setView('public')} onAuthenticated={s=>{setSession(s);setView('matches')}}/>;
 if(view==='matches') return <MatchesScreen session={session} onBack={()=>setView('public')} onLogin={()=>setView('login')} onMember={()=>setView('member')} onCommand={()=>setView('command')}/>;
 if(view==='command')return <CommandCenter session={session} brand={<Brand onHome={()=>setView('public')}/>} onBack={()=>setView('matches')}/>;
 return <div className="app-shell">
  <aside className={menu?'sidebar open':'sidebar'}><div className="side-top"><Brand onHome={()=>setView('public')}/><button className="icon-btn mobile" onClick={()=>setMenu(false)}><X/></button></div><nav>
   <Nav icon={<LayoutDashboard/>} label="Dashboard" active={view==='admin'||view==='member'} onClick={()=>setView(view==='member'?'member':'admin')}/>
   <Nav icon={<Goal/>} label="Command Center" active={false} badge="LIVE" onClick={()=>setView('command')}/>
   {['Matches','Members','Teams','Tournaments','Finance','Statistics','Polls','Announcements'].map((x,i)=><Nav key={x} icon={[<CalendarDays/>,<Users/>,<Shield/>,<Trophy/>,<Wallet/>,<Activity/>,<CheckCircle2/>,<Bell/>][i]} label={x}/>)}
  </nav><div className="profile"><div className="avatar">JK</div><div><b>Jaseel K.</b><small>Super Admin</small></div><MoreHorizontal/></div></aside>
  <main><header className="topbar"><button className="icon-btn mobile" onClick={()=>setMenu(true)}><Menu/></button><div className="search"><Search/><span>Search QFK…</span><kbd>⌘ K</kbd></div><div className="top-actions"><button className="icon-btn"><Bell/><i/></button><button className="ghost" onClick={()=>{api.logout();setSession(null);setView('public')}}><LogOut/> <span>Sign out</span></button></div></header>
  {view==='member'?<Member onCommand={()=>setView('command')}/>:<Admin onCommand={()=>setView('command')}/>}</main>
 </div>}
function Nav(p:{icon:React.ReactNode,label:string,active?:boolean,badge?:string,onClick?:()=>void}){return <button className={'nav '+(p.active?'active':'')} onClick={p.onClick}><span>{p.icon}</span>{p.label}{p.badge&&<em>{p.badge}</em>}</button>}

function Public({session,onMatches,onLogin}:{session:Session|null,onMatches:()=>void,onLogin:()=>void}){return <div className="public"><header className="public-nav"><Brand/><nav><a href="#about">About</a><button className="nav-link" onClick={onMatches}>Matches</button><a href="#teams">Teams</a><a href="#community">Community</a></nav><button className="nav-login" onClick={onLogin}>{session?'My account':'Member login'} <ChevronRight/></button></header>
 <section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> Qatar's football community</div><h1>Football brings us <em>together.</em></h1><p>Play. Connect. Grow. Join a community built around weekly football, lasting friendships and the beautiful game in Qatar.</p><div className="hero-actions"><button className="primary" onClick={onLogin}>{session?'View matches':'Join QFK'} <ArrowUpRight/></button><button className="secondary" onClick={onMatches}>Upcoming matches <CalendarDays/></button></div><div className="social-proof"><div className="faces"><span>JK</span><span>FA</span><span>NA</span><span>+24</span></div><p><b>240+ active members</b><br/>playing across Qatar</p></div></div><div className="hero-art"><img className="hero-photo" src={`${import.meta.env.BASE_URL}images/qfk-matchday-community.png`} alt="QFK community players greeting each other before an evening match in Qatar"/><div className="photo-shade"/><div className="match-ticket"><span className="live-dot">REGISTRATION OPEN</span><h3>Friday Community Match</h3><div><CalendarDays/> 11 September · 8:00 PM</div><div><MapPin/> Al Sadd Sports Club</div><footer><span><b>14</b> / 16 players</span><button onClick={onMatches}>View matches</button></footer></div><div className="float-stat"><Trophy/><span><b>128</b> matches played</span></div><span className="photo-caption">MATCHDAY IN DOHA · QFK COMMUNITY</span></div></section>
 <div className="matchday-ribbon"><span><i/> NEXT MATCH</span><b>FRIDAY COMMUNITY MATCH #128</b><span>11 SEP · 8:00 PM</span><span>AL SADD SPORTS CLUB</span><button onClick={onMatches}>VIEW MATCHES <ArrowUpRight/></button></div>
 <section className="stats" id="community">{[['240+','Members'],['128','Matches played'],['86','Active players'],['742','Goals scored'],['12','Tournaments']].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</section>
 <section className="section" id="matches"><div className="section-head"><div><small>NEXT ON THE PITCH</small><h2>Upcoming matches</h2></div><button onClick={onMatches}>View all fixtures <ChevronRight/></button></div><div className="game-grid">{games.map(g=><article className="game-card" key={g.title}><div className="datebox"><b>{g.day}</b><span>{g.date}</span></div><div><span className={'pill '+g.tone}>{g.tone==='open'?'Registration open':'Upcoming'}</span><h3>{g.title}</h3><p><MapPin/> {g.meta}</p></div><div className="slots"><Users/><b>{g.slots}</b><small>players</small></div><button aria-label={`Open ${g.title}`} onClick={onMatches}><ChevronRight/></button></article>)}</div></section>
 <section className="about" id="about"><div><small>MORE THAN A MATCH</small><h2>A place to play.<br/>A community to belong.</h2></div><p>Qatar Football Koottam connects football lovers across Qatar—from casual Friday players to competitive squads. Every match is organized, every member matters, and everyone has a place on the pitch.</p></section>
 <section className="team-feature" id="teams"><div className="team-mark">QU<span>FC</span></div><div><small>OUR COMPETITIVE TEAM</small><h2>Qatar United FC</h2><p>Representing the QFK community in tournaments and competitive fixtures across Qatar.</p><button>Meet the squad <ChevronRight/></button></div><div className="team-record"><div><b>18</b><span>Squad</span></div><div><b>7</b><span>Matches</span></div><div><b>4</b><span>Wins</span></div></div></section>
 <footer className="site-footer"><Brand/><p>Football. Friendship. Community.<br/>Made with pride in Qatar.</p><span>© 2026 Qatar Football Koottam</span></footer></div>}

function AuthScreen({resetToken,onBack,onAuthenticated}:{resetToken:string,onBack:()=>void,onAuthenticated:(s:Session)=>void}){
 const [mode,setMode]=useState<'login'|'register'|'forgot'|'reset'>(resetToken?'reset':'login');
 const [fullName,setFullName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [confirmPassword,setConfirmPassword]=useState('');
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 function changeMode(next:typeof mode){setMode(next);setError('');setNotice('');setPassword('');setConfirmPassword('')}
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{if(mode==='forgot'){await api.forgotPassword(email);setNotice('If that email belongs to a QFK account, a reset link is on its way. Please check your inbox and spam folder.')}else if(mode==='reset'){if(password!==confirmPassword)throw new Error('Passwords do not match');await api.resetPassword(resetToken,password);history.replaceState({},'',location.pathname);setNotice('Your password has been changed. You can now log in.');setMode('login');setPassword('');setConfirmPassword('')}else{const s=mode==='login'?await api.login(email,password):await api.register(fullName,email,password);onAuthenticated(s)}}catch(e){setError(e instanceof Error?e.message:'Unable to continue. Please try again.')}finally{setBusy(false)}}
 const heading=mode==='login'?'Welcome back':mode==='register'?'Join QFK':mode==='forgot'?'Reset your password':'Choose a new password';
 const intro=mode==='login'?'Log in to register for upcoming matches.':mode==='register'?'Create your member account to get started.':mode==='forgot'?'Enter your member email and we will send a secure reset link.':'Use at least 10 characters for your new password.';
 return <div className="portal-page"><header className="portal-nav"><Brand onHome={onBack}/><button className="secondary" onClick={onBack}>Back to home</button></header><main className="auth-layout"><section className="auth-story"><small>QFK MEMBER ACCESS</small><h1>Your football community,<br/><em>all in one place.</em></h1><p>Register for matches, follow your position and keep your QFK activity together.</p><div><CheckCircle2/> Live match availability</div><div><CheckCircle2/> Instant registration status</div><div><CheckCircle2/> One secure member account</div></section><form className="auth-card" onSubmit={submit}>{(mode==='login'||mode==='register')&&<div className="auth-tabs"><button type="button" className={mode==='login'?'active':''} onClick={()=>changeMode('login')}>Log in</button><button type="button" className={mode==='register'?'active':''} onClick={()=>changeMode('register')}>Create account</button></div>}<h2>{heading}</h2><p>{intro}</p>{mode==='register'&&<label>Full name<input required maxLength={160} value={fullName} onChange={e=>setFullName(e.target.value)} placeholder="Your full name"/></label>}{mode!=='reset'&&<label>Email address<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label>}{mode!=='forgot'&&<label>Password<input required type="password" minLength={mode==='login'?1:10} value={password} onChange={e=>setPassword(e.target.value)} placeholder={mode==='login'?'Your password':'At least 10 characters'}/></label>}{mode==='reset'&&<label>Confirm password<input required type="password" minLength={10} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} placeholder="Repeat your new password"/></label>}{mode==='login'&&<button className="forgot-link" type="button" onClick={()=>changeMode('forgot')}>Forgot password?</button>}{error&&<div className="form-error" role="alert">{error}</div>}{notice&&<div className="status-message success" role="status">{notice}</div>}<button className="primary auth-submit" disabled={busy}>{busy?'Please wait…':mode==='login'?'Log in':mode==='register'?'Create account':mode==='forgot'?'Send reset link':'Reset password'}</button>{(mode==='forgot'||mode==='reset')?<button className="back-login" type="button" onClick={()=>changeMode('login')}>Back to member login</button>:<small>By continuing, you agree to follow QFK community guidelines.</small>}</form></main></div>
}

function MatchesScreen({session,onBack,onLogin,onMember,onCommand}:{session:Session|null,onBack:()=>void,onLogin:()=>void,onMember:()=>void,onCommand:()=>void}){
 const [matches,setMatches]=useState<Match[]>([]);const [loading,setLoading]=useState(Boolean(session));const [error,setError]=useState('');const [notice,setNotice]=useState('');const [joining,setJoining]=useState('');
 useEffect(()=>{if(!session)return;api.matches().then(setMatches).catch(e=>setError(e instanceof Error?e.message:'Matches could not be loaded.')).finally(()=>setLoading(false))},[session]);
 async function join(matchId:string){setJoining(matchId);setError('');setNotice('');try{const result=await api.registerForMatch(matchId) as {status?:string;waitlistPosition?:number};setNotice(result.status==='WAITLISTED'?`You joined the waitlist${result.waitlistPosition?` at position ${result.waitlistPosition}`:''}.`:'Registration confirmed. You are in the match!');setMatches(await api.matches())}catch(e){setError(e instanceof Error?e.message:'Registration failed.')}finally{setJoining('')}}
 return <div className="portal-page matches-page"><header className="portal-nav"><Brand onHome={onBack}/><div><button className="secondary" onClick={onBack}>Home</button>{canManageMatches(session)&&<button className="secondary cc-access-link" onClick={onCommand}><Goal/> Command Center</button>}{session?<button className="primary" onClick={onMember}>My dashboard</button>:<button className="primary" onClick={onLogin}>Member login</button>}</div></header><main className="matches-main"><div className="matches-heading"><div><small>NEXT ON THE PITCH</small><h1>Upcoming matches</h1><p>See availability and reserve your place in the QFK lineup.</p></div>{session&&<span className="signed-in"><CheckCircle2/> Signed in</span>}</div>{notice&&<div className="status-message success" role="status">{notice}</div>}{error&&<div className="status-message error" role="alert">{error}</div>}{!session?<section className="login-prompt"><div><Shield/><span><small>MEMBERS ONLY</small><h2>Log in to see live availability</h2><p>Your account is required to view current matches and register securely.</p></span></div><button className="primary" onClick={onLogin}>Log in or join QFK <ArrowUpRight/></button></section>:loading?<div className="loading-card">Waking up the match service… This may take up to a minute on the first visit.</div>:matches.length===0?<div className="empty-state"><CalendarDays/><h2>No matches are open yet</h2><p>Check back soon. New QFK fixtures will appear here as soon as they are published.</p></div>:<div className="live-match-grid">{matches.map(m=>{const start=new Date(m.startsAt);const available=Math.max(0,m.maximumPlayers-m.confirmedPlayers);return <article className="live-match-card" key={m.id}><div className="live-date"><b>{start.toLocaleDateString('en-QA',{weekday:'short'}).toUpperCase()}</b><strong>{start.getDate()}</strong><span>{start.toLocaleDateString('en-QA',{month:'short'}).toUpperCase()}</span></div><div className="live-match-copy"><span className={'pill '+(available?'open':'soon')}>{available?`${available} places available`:'Waitlist available'}</span><h2>{m.title}</h2><p><CalendarDays/> {start.toLocaleString('en-QA',{dateStyle:'medium',timeStyle:'short'})}</p><p><MapPin/> {m.venue}</p><div className="capacity"><span><Users/> {m.confirmedPlayers} / {m.maximumPlayers} confirmed</span><span>{m.registrationFee} {m.currency}</span></div></div><button className="primary" disabled={joining===m.id} onClick={()=>join(m.id)}>{joining===m.id?'Registering…':available?'Register now':'Join waitlist'}</button></article>})}</div>}</main></div>
}

function PageIntro({eyebrow,title,sub,action}:{eyebrow:string,title:string,sub:string,action?:React.ReactNode}){return <div className="page-intro"><div><small>{eyebrow}</small><h1>{title}</h1><p>{sub}</p></div>{action}</div>}
function Member({onCommand}:{onCommand:()=>void}){return <div className="page"><PageIntro eyebrow="FRIDAY, 5 SEPTEMBER" title="Good evening, Jaseel 👋" sub="Your next game is six days away."/><div className="member-grid"><article className="next-match"><div className="card-label"><span className="live-dot">REGISTRATION OPEN</span><span>#128</span></div><h2>Friday Community Match</h2><p><CalendarDays/> Friday, 11 September · 8:00–10:00 PM</p><p><MapPin/> Al Sadd Sports Club</p><div className="registration-row"><div><CheckCircle2/><span><b>You're confirmed</b><small>Registered #3 · Paid</small></span></div><button onClick={onCommand}>View match <ChevronRight/></button></div></article><article className="my-stats"><div className="card-title"><h3>My season</h3><button>View stats</button></div><div className="stat-ring"><div><b>92%</b><span>Attendance</span></div></div><div className="mini-stats"><span><b>18</b>Matches</span><span><b>7</b>Goals</span><span><b>5</b>Assists</span></div></article></div><h2 className="block-title">Coming up</h2><div className="compact-games">{games.map(g=><div><div className="datebox"><b>{g.day}</b><span>{g.date}</span></div><span><b>{g.title}</b><small>{g.meta}</small></span><ChevronRight/></div>)}</div><div className="lower-grid"><article><div className="card-title"><h3>Announcements</h3><button>See all</button></div><div className="announcement"><span>IMPORTANT</span><b>New season registration is now open</b><small>2 hours ago</small></div></article><article><div className="card-title"><h3>Quick poll</h3><small>Closes tomorrow</small></div><b>Preferred ground for next Friday?</b><div className="poll"><button>Al Sadd <span>64%</span></button><button>Doha Sports Park <span>36%</span></button></div></article></div></div>}
function Admin({onCommand}:{onCommand:()=>void}){return <div className="page"><PageIntro eyebrow="ADMIN OVERVIEW" title="QFK at a glance" sub="Friday, 5 September 2026" action={<button className="primary" onClick={onCommand}>Open Command Center <ArrowUpRight/></button>}/><div className="metric-grid"><Metric icon={<CalendarDays/>} label="Next match" value="6 days" note="11 Sep · Al Sadd"/><Metric icon={<Users/>} label="Registered" value="14 / 16" note="2 slots remaining"/><Metric icon={<Wallet/>} label="Payments pending" value="20 QAR" note="2 players"/><Metric icon={<Activity/>} label="Active members" value="86" note="+8 this month"/><Metric icon={<Trophy/>} label="QFK fund" value="3,420" note="QAR available"/></div><div className="admin-grid"><article className="admin-match"><div className="card-title"><div><span className="live-dot">NEXT MATCH</span><h2>Friday Community Match #128</h2></div><button onClick={onCommand}>Manage <ChevronRight/></button></div><div className="match-details"><span><CalendarDays/><b>11 Sep</b><small>Friday · 8:00 PM</small></span><span><MapPin/><b>Al Sadd</b><small>Sports Club</small></span><span><Users/><b>14 / 16</b><small>2 waitlisted</small></span><span><Wallet/><b>120 QAR</b><small>collected</small></span></div></article><article><div className="card-title"><h3>Needs attention</h3><span className="count">4</span></div>{['2 match payments pending','3 members inactive for 8+ weeks','Tournament shortlist due Sunday'].map((x,i)=><div className="attention"><span className={'alert a'+i}>!</span><b>{x}</b><ChevronRight/></div>)}</article></div><div className="activity-card"><div className="card-title"><h3>Recent activity</h3><button>View all</button></div>{['Fasil Rahman joined Match #128','Nashid Ali completed payment','Admin published Qatar United FC squad','Ashiq voted in “Next match ground”'].map((x,i)=><div className="activity-row"><span className={'activity-icon i'+i}>{i===1?'₹':i===2?'⚽':'✓'}</span><b>{x}</b><small>{['12 min ago','28 min ago','2 hours ago','3 hours ago'][i]}</small></div>)}</div></div>}
function Metric({icon,label,value,note}:{icon:React.ReactNode,label:string,value:string,note:string}){return <article className="metric"><span>{icon}</span><small>{label}</small><b>{value}</b><p>{note}</p></article>}
createRoot(document.getElementById('root')!).render(<BrowserRouter><App/></BrowserRouter>);
