import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,useNavigate} from 'react-router-dom';
import {CalendarDays,MapPin,Users,Trophy,Wallet,ChevronRight,Bell,LayoutDashboard,Shield,Menu,X,Clock,CheckCircle2,UserRound,ArrowUpRight,Activity,Goal,LogOut,Search,MoreHorizontal} from 'lucide-react';
import './global-styles.css';
import {AlternateHome} from './alternate-home';
import './alternate-home.css';

type View='public'|'member'|'admin'|'command';
const players=[['1','Jaseel Kareem','Midfielder','Experienced','PAID','PRESENT'],['2','Fasil Rahman','Striker','Experienced','PAID','PRESENT'],['3','Nashid Ali','Centre Back','Intermediate','PAID','—'],['4','Shameer K','Goalkeeper','Experienced','UNPAID','—'],['5','Ashiq P','Right Wing','Intermediate','PAID','—'],['6','Riyas M','Left Back','Intermediate','UNPAID','—']];
const games=[{day:'FRI',date:'11 SEP',title:'Friday Community Match #128',meta:'8:00 PM · Al Sadd Sports Club',slots:'14 / 16',tone:'open'},{day:'FRI',date:'18 SEP',title:'QFK Friday Night Football',meta:'8:30 PM · Doha Sports Park',slots:'Registration soon',tone:'soon'}];

function Brand(){return <button className="brand" onClick={()=>location.hash=''}><span className="crest">Q</span><span><b>QFK</b><small>QATAR FOOTBALL KOOTTAM</small></span></button>}
function App(){const [view,setView]=useState<View>(location.pathname==='/alternate'?'alternate' as View:'public'); const [menu,setMenu]=useState(false); const [tab,setTab]=useState('Overview');
 if((view as string)==='alternate') return <AlternateHome onEnter={()=>setView('member')} onOriginal={()=>{history.pushState({},'', '/');setView('public')}}/>;
 if(view==='public') return <Public onEnter={()=>setView('member')} onAdmin={()=>setView('admin')}/>;
 const isCommand=view==='command'; return <div className="app-shell">
  <aside className={menu?'sidebar open':'sidebar'}><div className="side-top"><Brand/><button className="icon-btn mobile" onClick={()=>setMenu(false)}><X/></button></div><nav>
   <Nav icon={<LayoutDashboard/>} label="Dashboard" active={view==='admin'||view==='member'} onClick={()=>setView(view==='member'?'member':'admin')}/>
   <Nav icon={<Goal/>} label="Command Center" active={isCommand} badge="LIVE" onClick={()=>setView('command')}/>
   {['Matches','Members','Teams','Tournaments','Finance','Statistics','Polls','Announcements'].map((x,i)=><Nav key={x} icon={[<CalendarDays/>,<Users/>,<Shield/>,<Trophy/>,<Wallet/>,<Activity/>,<CheckCircle2/>,<Bell/>][i]} label={x}/>)}
  </nav><div className="profile"><div className="avatar">JK</div><div><b>Jaseel K.</b><small>Super Admin</small></div><MoreHorizontal/></div></aside>
  <main><header className="topbar"><button className="icon-btn mobile" onClick={()=>setMenu(true)}><Menu/></button><div className="search"><Search/><span>Search QFK…</span><kbd>⌘ K</kbd></div><div className="top-actions"><button className="icon-btn"><Bell/><i/></button><button className="ghost" onClick={()=>setView('public')}><LogOut/> <span>Sign out</span></button></div></header>
  {isCommand?<Command tab={tab} setTab={setTab}/>:view==='member'?<Member onCommand={()=>setView('command')}/>:<Admin onCommand={()=>setView('command')}/>}</main>
 </div>}
function Nav(p:{icon:React.ReactNode,label:string,active?:boolean,badge?:string,onClick?:()=>void}){return <button className={'nav '+(p.active?'active':'')} onClick={p.onClick}><span>{p.icon}</span>{p.label}{p.badge&&<em>{p.badge}</em>}</button>}

function Public({onEnter,onAdmin}:{onEnter:()=>void,onAdmin:()=>void}){return <div className="public"><header className="public-nav"><Brand/><nav><a href="#about">About</a><a href="#matches">Matches</a><a href="#teams">Teams</a><a href="#community">Community</a></nav><button className="nav-login" onClick={onAdmin}>Member login <ChevronRight/></button></header>
 <section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> Qatar's football community</div><h1>Football brings us <em>together.</em></h1><p>Play. Connect. Grow. Join a community built around weekly football, lasting friendships and the beautiful game in Qatar.</p><div className="hero-actions"><button className="primary" onClick={onEnter}>Join QFK <ArrowUpRight/></button><button className="secondary" onClick={()=>document.querySelector('#matches')?.scrollIntoView()}>Upcoming matches <CalendarDays/></button></div><div className="social-proof"><div className="faces"><span>JK</span><span>FA</span><span>NA</span><span>+24</span></div><p><b>240+ active members</b><br/>playing across Qatar</p></div></div><div className="hero-art"><img className="hero-photo" src="/images/qfk-matchday-community.png" alt="QFK community players greeting each other before an evening match in Qatar"/><div className="photo-shade"/><div className="match-ticket"><span className="live-dot">REGISTRATION OPEN</span><h3>Friday Community Match</h3><div><CalendarDays/> 11 September · 8:00 PM</div><div><MapPin/> Al Sadd Sports Club</div><footer><span><b>14</b> / 16 players</span><button onClick={onEnter}>Join match</button></footer></div><div className="float-stat"><Trophy/><span><b>128</b> matches played</span></div><span className="photo-caption">MATCHDAY IN DOHA · QFK COMMUNITY</span></div></section>
 <div className="matchday-ribbon"><span><i/> NEXT MATCH</span><b>FRIDAY COMMUNITY MATCH #128</b><span>11 SEP · 8:00 PM</span><span>AL SADD SPORTS CLUB</span><button onClick={onEnter}>2 SPOTS LEFT <ArrowUpRight/></button></div>
 <section className="stats" id="community">{[['240+','Members'],['128','Matches played'],['86','Active players'],['742','Goals scored'],['12','Tournaments']].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</section>
 <section className="section" id="matches"><div className="section-head"><div><small>NEXT ON THE PITCH</small><h2>Upcoming matches</h2></div><button>View all fixtures <ChevronRight/></button></div><div className="game-grid">{games.map(g=><article className="game-card"><div className="datebox"><b>{g.day}</b><span>{g.date}</span></div><div><span className={'pill '+g.tone}>{g.tone==='open'?'Registration open':'Upcoming'}</span><h3>{g.title}</h3><p><MapPin/> {g.meta}</p></div><div className="slots"><Users/><b>{g.slots}</b><small>players</small></div><button onClick={onEnter}><ChevronRight/></button></article>)}</div></section>
 <section className="about" id="about"><div><small>MORE THAN A MATCH</small><h2>A place to play.<br/>A community to belong.</h2></div><p>Qatar Football Koottam connects football lovers across Qatar—from casual Friday players to competitive squads. Every match is organized, every member matters, and everyone has a place on the pitch.</p></section>
 <section className="team-feature" id="teams"><div className="team-mark">QU<span>FC</span></div><div><small>OUR COMPETITIVE TEAM</small><h2>Qatar United FC</h2><p>Representing the QFK community in tournaments and competitive fixtures across Qatar.</p><button>Meet the squad <ChevronRight/></button></div><div className="team-record"><div><b>18</b><span>Squad</span></div><div><b>7</b><span>Matches</span></div><div><b>4</b><span>Wins</span></div></div></section>
 <footer className="site-footer"><Brand/><p>Football. Friendship. Community.<br/>Made with pride in Qatar.</p><span>© 2026 Qatar Football Koottam</span></footer></div>}

function PageIntro({eyebrow,title,sub,action}:{eyebrow:string,title:string,sub:string,action?:React.ReactNode}){return <div className="page-intro"><div><small>{eyebrow}</small><h1>{title}</h1><p>{sub}</p></div>{action}</div>}
function Member({onCommand}:{onCommand:()=>void}){return <div className="page"><PageIntro eyebrow="FRIDAY, 5 SEPTEMBER" title="Good evening, Jaseel 👋" sub="Your next game is six days away."/><div className="member-grid"><article className="next-match"><div className="card-label"><span className="live-dot">REGISTRATION OPEN</span><span>#128</span></div><h2>Friday Community Match</h2><p><CalendarDays/> Friday, 11 September · 8:00–10:00 PM</p><p><MapPin/> Al Sadd Sports Club</p><div className="registration-row"><div><CheckCircle2/><span><b>You're confirmed</b><small>Registered #3 · Paid</small></span></div><button onClick={onCommand}>View match <ChevronRight/></button></div></article><article className="my-stats"><div className="card-title"><h3>My season</h3><button>View stats</button></div><div className="stat-ring"><div><b>92%</b><span>Attendance</span></div></div><div className="mini-stats"><span><b>18</b>Matches</span><span><b>7</b>Goals</span><span><b>5</b>Assists</span></div></article></div><h2 className="block-title">Coming up</h2><div className="compact-games">{games.map(g=><div><div className="datebox"><b>{g.day}</b><span>{g.date}</span></div><span><b>{g.title}</b><small>{g.meta}</small></span><ChevronRight/></div>)}</div><div className="lower-grid"><article><div className="card-title"><h3>Announcements</h3><button>See all</button></div><div className="announcement"><span>IMPORTANT</span><b>New season registration is now open</b><small>2 hours ago</small></div></article><article><div className="card-title"><h3>Quick poll</h3><small>Closes tomorrow</small></div><b>Preferred ground for next Friday?</b><div className="poll"><button>Al Sadd <span>64%</span></button><button>Doha Sports Park <span>36%</span></button></div></article></div></div>}
function Admin({onCommand}:{onCommand:()=>void}){return <div className="page"><PageIntro eyebrow="ADMIN OVERVIEW" title="QFK at a glance" sub="Friday, 5 September 2026" action={<button className="primary" onClick={onCommand}>Open Command Center <ArrowUpRight/></button>}/><div className="metric-grid"><Metric icon={<CalendarDays/>} label="Next match" value="6 days" note="11 Sep · Al Sadd"/><Metric icon={<Users/>} label="Registered" value="14 / 16" note="2 slots remaining"/><Metric icon={<Wallet/>} label="Payments pending" value="20 QAR" note="2 players"/><Metric icon={<Activity/>} label="Active members" value="86" note="+8 this month"/><Metric icon={<Trophy/>} label="QFK fund" value="3,420" note="QAR available"/></div><div className="admin-grid"><article className="admin-match"><div className="card-title"><div><span className="live-dot">NEXT MATCH</span><h2>Friday Community Match #128</h2></div><button onClick={onCommand}>Manage <ChevronRight/></button></div><div className="match-details"><span><CalendarDays/><b>11 Sep</b><small>Friday · 8:00 PM</small></span><span><MapPin/><b>Al Sadd</b><small>Sports Club</small></span><span><Users/><b>14 / 16</b><small>2 waitlisted</small></span><span><Wallet/><b>120 QAR</b><small>collected</small></span></div></article><article><div className="card-title"><h3>Needs attention</h3><span className="count">4</span></div>{['2 match payments pending','3 members inactive for 8+ weeks','Tournament shortlist due Sunday'].map((x,i)=><div className="attention"><span className={'alert a'+i}>!</span><b>{x}</b><ChevronRight/></div>)}</article></div><div className="activity-card"><div className="card-title"><h3>Recent activity</h3><button>View all</button></div>{['Fasil Rahman joined Match #128','Nashid Ali completed payment','Admin published Qatar United FC squad','Ashiq voted in “Next match ground”'].map((x,i)=><div className="activity-row"><span className={'activity-icon i'+i}>{i===1?'₹':i===2?'⚽':'✓'}</span><b>{x}</b><small>{['12 min ago','28 min ago','2 hours ago','3 hours ago'][i]}</small></div>)}</div></div>}
function Metric({icon,label,value,note}:{icon:React.ReactNode,label:string,value:string,note:string}){return <article className="metric"><span>{icon}</span><small>{label}</small><b>{value}</b><p>{note}</p></article>}
function Command({tab,setTab}:{tab:string,setTab:(x:string)=>void}){const tabs=['Overview','Registration','Teams','Payments','Attendance','Live / Result','Statistics','Activity Log'];return <div className="command"><div className="command-hero"><div className="breadcrumbs">Matches <ChevronRight/> Match #128 <ChevronRight/> Command Center</div><div className="command-title"><div><span className="live-dot">REGISTRATION OPEN</span><h1>Friday Community Match <span>#128</span></h1><p><CalendarDays/> Fri, 11 Sep · 8:00–10:00 PM <i/> <MapPin/> Al Sadd Sports Club <a>Open map ↗</a></p></div><button className="secondary">•••</button></div><div className="command-summary">{[['14 / 16','CONFIRMED'],['2','WAITLIST'],['120 QAR','COLLECTED'],['20 QAR','PENDING'],['—','ATTENDANCE']].map(x=><div><b>{x[0]}</b><span>{x[1]}</span></div>)}</div></div><div className="tabbar">{tabs.map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>{tab==='Overview'?<Overview setTab={setTab}/>:<Registration tab={tab}/>}</div>}
function Overview({setTab}:{setTab:(x:string)=>void}){return <div className="command-body"><div className="quick"><b>Quick actions</b><button onClick={()=>setTab('Teams')}><Users/> Generate teams</button><button onClick={()=>setTab('Attendance')}><CheckCircle2/> Mark attendance</button><button onClick={()=>setTab('Payments')}><Wallet/> Record payment</button><button className="start"><Goal/> Start match</button></div><div className="overview-metrics">{[['14','Registered','2 slots remaining'],['2','Waitlist','First: Ahmed R.'],['12','Paid','2 payments pending'],['140','Expected','120 QAR collected'],['100','Ground cost','40 QAR balance']].map((x,i)=><article><span className={'dot d'+i}/><small>{x[1]}</small><b>{x[0]}{i>2&&<em> QAR</em>}</b><p>{x[2]}</p></article>)}</div><div className="cc-grid"><article><div className="card-title"><h3>Registration</h3><button onClick={()=>setTab('Registration')}>View all <ChevronRight/></button></div><div className="progress-label"><span>14 confirmed</span><b>88% full</b></div><div className="progress"><i/></div><div className="avatar-line"><div className="faces"><span>JK</span><span>FA</span><span>NA</span><span>SK</span><span>+10</span></div><p>2 players on waitlist</p></div></article><article><div className="card-title"><h3>Payments</h3><button onClick={()=>setTab('Payments')}>Manage <ChevronRight/></button></div><div className="money"><div><small>COLLECTED</small><b>120 <em>QAR</em></b></div><div><small>PENDING</small><b className="orange">20 <em>QAR</em></b></div></div><div className="progress moneybar"><i/></div><p className="muted">12 of 14 confirmed players have paid</p></article><article className="recent"><div className="card-title"><h3>Recent activity</h3><button>View log</button></div>{['Fasil Rahman joined the match','Nashid Ali completed payment','Ahmed R. joined the waitlist','Registration opened'].map((x,i)=><div className="activity-row"><span className={'activity-icon i'+i}>{i===1?'₹':'✓'}</span><b>{x}</b><small>{['12 min','28 min','1 hr','3 days'][i]}</small></div>)}</article></div><div className="mobile-sticky"><button><Users/> Players</button><button><CheckCircle2/> Attendance</button><button><Wallet/> Payments</button><button className="start"><Goal/> Start</button></div></div>}
function Registration({tab}:{tab:string}){if(tab!=='Registration')return <div className="empty-tab"><span>{tab==='Teams'?'⚽':tab==='Payments'?'₹':tab==='Attendance'?'✓':'◌'}</span><h2>{tab}</h2><p>This operational workspace is prepared for the next implementation phase.</p><button className="primary">Continue setup <ChevronRight/></button></div>;return <div className="command-body"><div className="table-head"><div><h2>Match players</h2><p>14 confirmed · 2 waitlisted</p></div><div><button className="secondary"><Search/> Search</button><button className="primary">+ Add player</button></div></div><div className="player-table"><div className="tr th"><span>#</span><span>Player</span><span>Position</span><span>Skill</span><span>Payment</span><span>Attendance</span><span/></div>{players.map(p=><div className="tr">{p.map((v,i)=><span className={i===4?'pay '+v.toLowerCase():i===5?'attend':''}>{i===1&&<i className="small-avatar">{v.split(' ').map(x=>x[0]).join('').slice(0,2)}</i>}{v}</span>)}<button className="icon-btn"><MoreHorizontal/></button></div>)}</div></div>}
createRoot(document.getElementById('root')!).render(<BrowserRouter><App/></BrowserRouter>);
