import {useEffect,useRef,useState,type PointerEvent as ReactPointerEvent} from 'react';
import {balancePlayers,fillSlots,formationSlots} from './lineup-positions';
import {exportPoster} from './lineup-poster';
import {api} from './api-client';
import {Users,Shirt,Scale,Save,Download,RotateCcw,GripVertical,UserPlus,Settings as SettingsIcon} from 'lucide-react';
import type {Row} from './operations';
type Player={registrationId:string;name:string;guest:boolean;side:string;position:string;preferredPosition:string;starter:boolean;x:number;y:number;shirtNumber:number};
type Settings={starterLimit:number;homeName:string;awayName:string;homeColor:string;awayColor:string;homeFormation:string;awayFormation:string};
type Props={match:Row;matchId:string;players:Row[];busy:boolean;onSaved:()=>void};
const defaults:Settings={starterLimit:7,homeName:'Home squad',awayName:'Away squad',homeColor:'#801735',awayColor:'#475463',homeFormation:'2-3-1',awayFormation:'2-3-1'};
const positions=['GOALKEEPER','DEFENDER','MIDFIELDER','FORWARD','UTILITY'];
const presets:Record<number,string[]>={2:['1'],3:['1-1'],4:['1-1-1','2-1'],5:['1-2-1','2-1-1'],6:['2-2-1','1-3-1'],7:['2-3-1','3-2-1'],8:['2-3-2','3-2-2'],9:['3-3-2','3-2-3'],10:['3-3-3','4-3-2'],11:['4-3-3','4-4-2','3-5-2']};
const validFormation=(value:string,limit:number)=>/^[1-9](?:-[1-9]){0,5}$/.test(value)&&value.split('-').reduce((n,v)=>n+Number(v),0)===limit-1;
export function SquadBoard({match,matchId,players,busy,onSaved}:Props){
 const [list,setList]=useState<Player[]>([]),[settings,setSettings]=useState<Settings>(defaults),[selected,setSelected]=useState<string|null>(null),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[search,setSearch]=useState(''),[poster,setPoster]=useState('');
 const [loading,setLoading]=useState(true),[exporting,setExporting]=useState(false);
 const [custom,setCustom]=useState({HOME:'',AWAY:''});
 const playerSnapshot=JSON.stringify(players);
 const suppressClick=useRef(false);
 const drag=useRef<{id:string;startX:number;startY:number;moved:boolean}|null>(null);
 useEffect(()=>{let active=true;setLoading(true);setDirty(false);setSelected(null);setError('');
  const initial:Player[]=players.map((r,i)=>({registrationId:String(r.id),name:String(r.player_name),guest:Boolean(r.guest_name),side:String(r.side??'UNASSIGNED'),position:String(r.position??'UTILITY'),preferredPosition:String(r.preferred_position??'UTILITY'),starter:r.starter!==false,x:Number(r.pitch_x??50),y:Number(r.pitch_y??50),shirtNumber:Number(r.shirt_number??i%99+1)}));setList(initial);
  api.operations<Row>(`/manage/matches/${matchId}/builder`).then(s=>{if(!active)return;const limit=Math.min(11,Math.max(Number(s.starter_limit),...['HOME','AWAY'].map(side=>initial.filter(p=>p.side===side&&p.starter).length))),homeFormation=validFormation(String(s.home_formation),limit)?String(s.home_formation):presets[limit][0],awayFormation=validFormation(String(s.away_formation),limit)?String(s.away_formation):presets[limit][0];setSettings({starterLimit:limit,homeName:String(s.home_name),awayName:String(s.away_name),homeColor:String(s.home_color),awayColor:String(s.away_color),homeFormation,awayFormation});
   let arranged=initial,changed=limit!==Number(s.starter_limit);for(const side of ['HOME','AWAY']){const starters=initial.filter(p=>p.side===side&&p.starter);if(starters.length>1&&starters.every(p=>p.x===50&&p.y===50)){arranged=formation(side,side==='HOME'?homeFormation:awayFormation,arranged);changed=true}}if(changed){setList(arranged);setDirty(true)}
  }).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[matchId,playerSnapshot]);
 const disabled=busy||saving||loading;
 function update(next:Player[]){setList(next);setDirty(true);setError('')}
 function assign(id:string,side:string,starter:boolean,x=50,y=50){const p=list.find(p=>p.registrationId===id);if(!p||disabled)return;if(side!=='UNASSIGNED'&&starter&&list.filter(q=>q.registrationId!==id&&q.side===side&&q.starter).length>=settings.starterLimit){setError(`This team already has ${settings.starterLimit} starters. Use its substitute bench.`);return}update(list.map(q=>q.registrationId===id?{...q,side,starter,x,y}:q));setSelected(null)}
 function changeSettings(p:Partial<Settings>){
  if(p.starterLimit){const limit=p.starterLimit,homeFormation=presets[limit][0],awayFormation=presets[limit][0],counts={HOME:0,AWAY:0};const next=list.map(q=>({...q,starter:q.side==='HOME'||q.side==='AWAY'?q.starter&&++counts[q.side]<=limit:q.starter}));setSettings(v=>({...v,...p,homeFormation,awayFormation}));setCustom({HOME:'',AWAY:''});update(formation('AWAY',awayFormation,formation('HOME',homeFormation,next)));return}
  setSettings(v=>({...v,...p}));setDirty(true);setError('')
 }
 function applyFormation(side:'HOME'|'AWAY',value:string){const clean=value.trim();if(!validFormation(clean,settings.starterLimit)){setError(`Formation must total ${settings.starterLimit-1} outfield players, plus one goalkeeper. Example: ${presets[settings.starterLimit][0]}.`);return}changeSettings(side==='HOME'?{homeFormation:clean}:{awayFormation:clean});update(formation(side,clean))}

 async function save(){setSaving(true);setError('');try{await api.operations(`/manage/matches/${matchId}/builder`,'PUT',{...settings,players:list.map(({name,guest,preferredPosition,...p})=>p)});setDirty(false);onSaved()}catch(e){setError(e instanceof Error?e.message:'Unable to save lineup')}finally{setSaving(false)}}
 function formation(side:string,value:string,base=list){const {assigned}=fillSlots(base.filter(p=>p.side===side&&p.starter),formationSlots(value,side));const mapped=new Map(assigned.map(p=>[p.registrationId,p]));return base.map(p=>mapped.get(p.registrationId)??p)}
 function shuffle(){update(balancePlayers([...list].sort(()=>Math.random()-.5),settings.homeFormation,settings.awayFormation))}
 function pointerDown(e:ReactPointerEvent,id:string){if(disabled||e.button!==0)return;suppressClick.current=false;drag.current={id,startX:e.clientX,startY:e.clientY,moved:false};e.currentTarget.setPointerCapture(e.pointerId)}
 function pointerMove(e:ReactPointerEvent){if(drag.current&&Math.hypot(e.clientX-drag.current.startX,e.clientY-drag.current.startY)>5)drag.current.moved=true}
 function pointerUp(e:ReactPointerEvent){const d=drag.current;drag.current=null;if(!d||!d.moved)return;suppressClick.current=true;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest<HTMLElement>('[data-lineup-zone]');if(!target)return;const zone=target.dataset.lineupZone!,rect=target.getBoundingClientRect();assign(d.id,target.dataset.side??'UNASSIGNED',zone==='pitch',Math.max(12,Math.min(88,100*(e.clientX-rect.left)/rect.width)),Math.max(8,Math.min(92,100*(e.clientY-rect.top)/rect.height)))}
 const token=(p:Player,color:string)=><button disabled={disabled} className={'lb-token'+(selected===p.registrationId?' selected':'')} onPointerDown={e=>pointerDown(e,p.registrationId)} onPointerMove={pointerMove} onPointerUp={pointerUp} onClick={()=>{if(suppressClick.current){suppressClick.current=false;return}setSelected(p.registrationId)}} aria-label={`Select ${p.name}`}><span className="lb-number" style={{background:color}}>{String(p.shirtNumber).padStart(2,'0')}</span><svg viewBox="0 0 48 48" aria-hidden="true"><path fill={color} stroke="#ffffff99" d="M13 3L20 6H28L35 3L47 14L38 23L34 19V45H14V19L10 23L1 14Z"/><text x="24" y="31" textAnchor="middle" fill="white" fontSize="17" fontWeight="bold">{p.shirtNumber}</text></svg><span className="lb-token-name">{p.name}<small className="lb-role">{p.position.toLowerCase().replace(/^./,c=>c.toUpperCase())}</small></span><small className={'cc-badge status-'+(p.guest?'guest':'member')}>{p.guest?'Guest':'Member'}</small><GripVertical className="lb-grip" size={16}/></button>;
 async function exportLineup(){setExporting(true);setError('');try{setPoster(await exportPoster(list,settings,match))}catch(e){setError(e instanceof Error?e.message:'Unable to export poster')}finally{setExporting(false)}}
 const picked=list.find(p=>p.registrationId===selected);
 return <section className="lineup-builder lb-reference">
 {error&&<p className="cc-error" role="alert">{error}</p>}
 {poster&&<div className="cc-modal-backdrop" onClick={()=>setPoster('')}><section className="lb-poster-preview" role="dialog" aria-modal="true" aria-label="Match poster preview" onClick={e=>e.stopPropagation()}><header><h2>Match poster</h2><button autoFocus className="secondary" onClick={()=>setPoster('')}>Close</button><a className="primary" href={poster} download={'qfk-match-'+String(match.match_number)+'.png'}>Download PNG</a></header><img src={poster} alt="Match poster with team players, positions, venue and Qatar date and time"/></section></div>}<div className="lb-toolbar"><label>Players per team<select aria-label="Players per team" disabled={disabled} value={settings.starterLimit} onChange={e=>changeSettings({starterLimit:Number(e.target.value)})}>{Array.from({length:10},(_,i)=>i+2).map(n=><option key={n} value={n}>{n}</option>)}</select></label><span className="lb-toolbar-spacer"/><button className="secondary" disabled={disabled} onClick={shuffle}><Scale size={17}/>Balance teams</button><button className="primary" disabled={disabled||!dirty} onClick={()=>void save()}><Save size={16}/>{saving?'Saving…':dirty?'Save lineup':'Lineup saved'}</button><details className="lb-more"><summary>More</summary><button className="secondary" disabled={disabled} onClick={()=>update(list.map(p=>({...p,side:'UNASSIGNED',starter:false})))}><RotateCcw size={15}/>Reset teams</button><button className="secondary" disabled={loading||exporting} onClick={()=>void exportLineup()}><Download size={15}/>{exporting?'Preparing poster…':'Export match poster'}</button></details></div>
 <p className="lb-instructions">Drag players between squads and benches, or select a player and use the assignment controls. Formations include one goalkeeper. Save lineup to keep your changes.</p>
{picked&&<div className="lb-selected"><strong>{picked.name}</strong><label>Shirt number<input disabled={disabled} type="number" min="1" max="99" value={picked.shirtNumber} onChange={e=>{const n=Number(e.target.value);if(n>=1&&n<=99)update(list.map(p=>p.registrationId===selected?{...p,shirtNumber:n}:p))}}/></label><label>Position<select disabled={disabled} value={picked.position} onChange={e=>update(list.map(p=>p.registrationId===selected?{...p,position:e.target.value}:p))}>{positions.map(p=><option key={p}>{p}</option>)}</select></label><button className="secondary" disabled={disabled} onClick={()=>assign(picked.registrationId,'HOME',true)}>Home pitch</button><button className="secondary" disabled={disabled} onClick={()=>assign(picked.registrationId,'AWAY',true)}>Away pitch</button><button className="secondary" disabled={disabled} onClick={()=>assign(picked.registrationId,'HOME',false)}>Home bench</button><button className="secondary" disabled={disabled} onClick={()=>assign(picked.registrationId,'AWAY',false)}>Away bench</button><button className="secondary" disabled={disabled} onClick={()=>assign(picked.registrationId,'UNASSIGNED',false)}>Return to available</button><button className="secondary" onClick={()=>setSelected(null)}>Close</button></div>}<div className="lb-layout">
 {(['HOME','AWAY'] as const).map(side=>{const home=side==='HOME',squad=list.filter(p=>p.side===side),color=home?settings.homeColor:settings.awayColor,current=home?settings.homeFormation:settings.awayFormation;return <article className="lb-team" key={side}>
 <div className="lb-card-title"><Shirt size={24} fill={color} color={color}/><h2>{home?settings.homeName:settings.awayName}<small>· {squad.length} players</small></h2></div>
 <div className="lb-team-controls"><label>Formation<select aria-label={'Formation for '+side.toLowerCase()} disabled={disabled} value={current} onChange={e=>applyFormation(side,e.target.value)}>{[...new Set([...presets[settings.starterLimit],current])].map(f=><option key={f} value={f}>{f}</option>)}</select></label><details className="lb-custom"><summary>Custom formation</summary><form onSubmit={e=>{e.preventDefault();applyFormation(side,custom[side])}}><label>Formation (defence to attack)<input aria-label={'Custom formation for '+side.toLowerCase()} value={custom[side]} disabled={disabled} placeholder={presets[settings.starterLimit][0]} maxLength={11} onChange={e=>setCustom(v=>({...v,[side]:e.target.value}))}/></label><small>Outfield total: {settings.starterLimit-1} + 1 goalkeeper</small><button className="secondary" disabled={disabled}>Apply formation</button></form></details><details className="lb-squad-settings"><summary aria-label={'Settings for '+side.toLowerCase()+' squad'}><SettingsIcon size={15}/></summary><label>Squad name<input aria-label={home?'Home squad name':'Away squad name'} disabled={disabled} value={home?settings.homeName:settings.awayName} maxLength={80} onChange={e=>changeSettings(home?{homeName:e.target.value}:{awayName:e.target.value})}/></label><label>Shirt color<input type="color" aria-label={home?'Home shirt color':'Away shirt color'} disabled={disabled} value={color} onChange={e=>changeSettings(home?{homeColor:e.target.value}:{awayColor:e.target.value})}/></label></details></div>
 <div className="lb-team-content"><div className={'lb-pitch'+(selected?' accepting':'')} data-lineup-zone="pitch" data-side={side} onClick={e=>{if(selected){const r=e.currentTarget.getBoundingClientRect();assign(selected,side,true,Math.max(12,Math.min(88,100*(e.clientX-r.left)/r.width)),Math.max(8,Math.min(92,100*(e.clientY-r.top)/r.height)))}}}><svg className="lb-markings" viewBox="0 0 100 150" preserveAspectRatio="none" aria-hidden="true"><rect x="2" y="2" width="96" height="146"/><path d="M2 75H98"/><circle cx="50" cy="75" r="12"/><circle cx="50" cy="75" r=".5"/><path d="M24 2V27H76V2M37 2V12H63V2M24 148V123H76V148M37 148V138H63V148"/><path d="M38 27Q50 43 62 27M38 123Q50 107 62 123"/></svg>{squad.filter(p=>p.starter).map(p=><div className="lb-on-pitch" key={p.registrationId} style={{left:p.x+'%',top:p.y+'%'}} onClick={e=>e.stopPropagation()}>{token(p,color)}</div>)}{!squad.some(p=>p.starter)&&<div className="lb-pitch-empty">Select or drag players to the pitch</div>}</div>
 <div className={'lb-bench'+(selected?' accepting':'')} data-lineup-zone="bench" data-side={side} onClick={()=>{if(selected)assign(selected,side,false)}}><h3>Bench ({squad.filter(p=>!p.starter).length})</h3><div>{squad.filter(p=>!p.starter).map(p=><div key={p.registrationId} onClick={e=>e.stopPropagation()}>{token(p,color)}<button disabled={disabled} className="lb-return" aria-label={'Return '+p.name+' to available'} onClick={()=>assign(p.registrationId,'UNASSIGNED',false)}>↩</button></div>)}</div>{!squad.some(p=>!p.starter)&&<p>Drop or tap here to add substitutes</p>}</div></div>
 <p className="lb-squad-count">{squad.filter(p=>p.starter).length} / {settings.starterLimit} starters · {squad.filter(p=>!p.starter).length} substitutes</p></article>})}
 <aside className="lb-available" data-lineup-zone="available" onClick={()=>{if(selected)assign(selected,'UNASSIGNED',false)}}><h2><Users size={21}/>Unassigned players ({list.filter(p=>p.side==='UNASSIGNED').length})</h2><input aria-label="Search available players" placeholder="Search players…" value={search} onClick={e=>e.stopPropagation()} onChange={e=>setSearch(e.target.value)}/>{list.filter(p=>p.side==='UNASSIGNED'&&p.name.toLowerCase().includes(search.toLowerCase())).map(p=><div key={p.registrationId} onClick={e=>e.stopPropagation()}>{token(p,p.guest?'#56616b':'#801735')}<button className="secondary lb-assign" disabled={disabled} onClick={()=>setSelected(p.registrationId)}><UserPlus size={14}/>Assign to team</button></div>)}{!list.some(p=>p.side==='UNASSIGNED')&&<p>All players assigned. Return players from either squad here.</p>}</aside>
 </div></section>
}

